openapi: 3.0.3
info:
  title: OSE Killer API
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /sign-up:
    post:
      tags:
        - Authentication
      summary: Envoyer une demande d'inscription
      description: Envoyer une demande d'inscription
      operationId: signUp
      requestBody:
        description: Demande d'inscription
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignUpRequest'
        required: true
      responses:
        '202':
          description: Demande en attente d'acceptation
        '400':
          description: Format invalide / Attribut(s) manquant(s)
        '409':
          description: Email non disponible
  /sign-in:
    post:
      tags:
        - Authentication
      summary: Envoyer une demande de connection
      description: Envoyer une demande de connection
      operationId: signIn
      requestBody:
        description: Demande de connection
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignInRequest'
        required: true
      responses:
        '200':
          description: Demande de connection accepté
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JwtResponse'
        '400':
          description: Format invalide / Attribut(s) manquant(s)
        '401':
          description: Informations d'identification invalides
  /sign-out:
    post:
      tags:
        - Authentication
      summary: Demande de révocation du refresh token
      description: Demande de révocation du refresh token
      operationId: signOut
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRequest'
        required: true
      responses:
        '200':
          description: Demande de révocation accepté
        '400':
          description: Format invalide / Attribut(s) manquant(s)
        '401':
          description: Token Invalide
        '403':
          description: Le token n'appartient pas à l'utilisateur
      security:
      - bearerAuth: []
  /refresh:
    post:
      tags:
        - Authentication
      summary: Demande d'un nouveau JWT Valide
      description: Demande d'un nouveau JWT
      operationId: refresh
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRequest'
        required: true
      responses:
        '200':
          description: Demande d'un nouveau JWT Valide accepté
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JwtResponse'
        '400':
          description: Format invalide / Attribut(s) manquant(s)
        '401':
          description: Token Invalide ou Expiré
        '403':
          description: Le token n'appartient pas à l'utilisateur
      security:
        - bearerAuth: []
        
  /user/validate:
    post:
      tags:
        - User
      summary: Valider une inscription utilisateur
      description: Valider une inscription utilisateur
      operationId: validateUser
      requestBody:
        description: Valider l'inscription d'un nouveau user
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserValidationRequest'
        required: true
      responses:
        '200':
          description: Validation a été complété
        '400':
          description: Format invalide / Attribut(s) manquant(s)
        '403':
          description: Requête non autorisée
      security:
        - bearerAuth: []
  /users:
    get:
      tags:
        - User
      summary: Retourne tous les utilisateurs
      description: Retourne tous les utilisateurs
      operationId: getUsers
      responses:
        '200':
          description: Les utilisateurs ont été envoyés
        '400':
          description: Format invalide / Attribut(s) manquant(s)
        '403':
          description: Requête non autorisée
      security:
        - bearerAuth: []
  /ping:
    get:
      tags:
        - Ping
      summary: Demande de ping
      description: Demande de ping
      operationId: ping
      responses:
        '200':
          description: Demande de ping reçu
  /ping/token:
    get:
      tags:
        - Ping
      summary: Demande de ping par un l'utilisateur autentifié
      description: Demande de ping par un l'utilisateur autentifié
      operationId: pingToken
      responses:
        '200':
          description: Demande de ping reçu
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthPingResponse'
        '403':
          description: Requête non autorisée
      security:
        - bearerAuth: []
  /student/{id}/cv:
    put:
      tags:
      - Student
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      summary: Téléverser le cv de format pdf d'un étudiant
      description: Téléverser le cv de format pdf d'un étudiant
      operationId: uploadCV
      requestBody:
        description: Téléverser un cv
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
        required: true
      responses:
        '200':
          description: Le fichier a été Téléversé
        '403':
          description: Requête non autorisée
      security:
        - bearerAuth: []
    get:
      tags:
      - Student
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      summary: Télécharger le cv de format pdf d'un étudiant
      description: Télécharger le cv de format pdf d'un étudiant
      operationId: downloadCV
      responses:
        '200':
          description: Le fichier a été Télécharger
          content:
            multipart/form-data:
              schema:
                type: object
                properties:
                  file:
                    type: string
                    format: binary
        '403':
          description: Requête non autorisée
      security:
        - bearerAuth: []
  /student/{id}/cv/validate:
    post:
      tags:
      - Student
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      summary: Valider le CV d'un étudiant
      description: Valider le cv de format pdf d'un étudiant
      operationId: validateCV
      requestBody:
        description: Valider le CV d'un étudiant
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CvValidationRequest'
        required: true
      responses:
        '200':
          description: Le CV à été Téléversé
        '403':
          description: Requête non autorisée
      security:
        - bearerAuth: []
components:
  securitySchemes:
      bearerAuth:
        type: http
        scheme: bearer
        bearerFormat: JWT
  schemas:
    JwtResponse:
      type: object
      properties:
        accessToken:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
        refreshToken:
          type: string
          example: 123e4567-e89b-12d3-a456-426614174000
        tokenType:
          type: string
          example: Bearer
    AuthPingResponse:
      type: object
      properties:
        email:
          type: string
          format: email
          example: hugol@example.com
        role:
          type: string
          example: STUDENT
    CvValidationRequest:
      type: object
      required:
        - valid
      properties:
        valid:
          type: boolean
          example: false
        feedBack:
          type: string
          example: Votre CV est trop long
    SignUpRequest:
      type: object
      required:
        - name
        - email
        - password
        - role
      properties:
        name:
          type: string
          example: Hugo Lantier
        email:
          type: string
          format: email
          example: hugol@example.com
        password:
          type: string
          example: vant8L52ANAp7U
        role:
          type: string
          example: STUDENT
          enum:
            - STUDENT
            - MANAGER
            - COMPANY
      xml:
        name: signUpRequest
    SignInRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          example: tesla.internship@example.com
        password:
          type: string
          example: vant8L52ANAp7U
      xml:
        name: signInRequest
    TokenRequest:
      type: object
      required:
        - refreshToken
      properties:
        refreshToken: 
          type: string
          example: 123e4567-e89b-12d3-a456-426614174000
      xml:
        name: signInRequest
    UserValidationRequest:
      type: object
      required:
        - valid
        - email
      properties:
        email:
          type: string
          format: email
          example: hugol@example.com
        valid:
          type: boolean
          example: true
      xml:
        name: userValidationRequest
